### ISSUE TITLE
Prowlarr indexers / VPN

### ISSUE THREAD

**Issue by Andrew-devweb** [AdrienPoupa/docker-compose-nas#143]
Hi everyone,
This is more a suggestion or feedback more than an issue, but I noticed that websites like "iknowwhatyoudownload.com" were marking my IP as having downloaded several torrents, despite qBitTorrent being behind VPN. It makes sense as simply indexing a file is routed to the user's network with the current setup, which is not ideal for privacy.

Now, according to the option part of the README file, it's suggested to:
_____________________________________________________________________
### Optional: Using the VPN for *arr apps

If you want to use the VPN for Prowlarr and other *arr applications, add the following block to all the desired containers:
```yml
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy
```
[...]
_____________________________________________________________________

Which makes sense, and would solve the indexing issue. But on https://trash-guides.info/Prowlarr/prowlarr-setup-proxy/ it's actually suggested NOT to put any *arr apps behind VPN, as it can break connection between services or end up with shadow bans for *arr services or metadata providers.

Additionally, with this docker-compose setup, the idea is for it to be pretty "plug and play" and not require excessive modifications from the user. Putting everything behind VPN would also mean changing the host for each service (JellySeerr > Radarr/Sonarr or Radarr/Sonarr/Lidarr themselves with their relevant configuration) and also homepage, as many of the APIs are now behind VPN and might need change or potentially exposing some services (I haven't tested that, but it's just a theory)

So what I ended up doing is using an additional solution not present in the current stack, but with minimal resource / configuration addition and adding tinyproxy for indexer reverse searching, like here:

 ```
 tinyproxy:
    image: vimagick/tinyproxy
    container_name: tinyproxy
    environment:
      - TZ=${TIMEZONE}
    network_mode: "service:vpn"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8888"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s
    depends_on:
      vpn:
        condition: service_healthy
```

which 
1) Uses the same VPN container as qBitTorrent-Web for VPN access (and doesn't require further configuration)
2) Performs the same health checks for container health (and requires VPN to also be working)

This way, adding indexers behind your current VPN setup is as easy as going to

Settings > Indexers > + > HTTP 
And then use "vpn" and "8888" as port.

No other implementation, configuration or setting is needed between all services.

Now, this **_might_** break indexers using FlareSolverr, but I set both tags and so far they appear to be still working.
It's more a proof of concept than anything, but I believe it can be a good implementation or solution instead of rerouting all containers within the VPN, as stated above
