### ISSUE TITLE
Guide for adding other docker services with traefik

### ISSUE THREAD

**Issue by wrapper** [AdrienPoupa/docker-compose-nas#41]
Hey

Love the script and the documentation makes it pretty straightforward to set up.

I'm trying to add other containers such as syncthing, pigallery. I got syncthing working easily enough but not sure how to get it to have the same URL structure (nas.domain.com/syncthing). pigallery requires nginx and those ports (80,443) are taken so again, I'm not sure how to configure that.

Would be awesome if there was documentation for adding other generic docker containers to the existing set up.

**Comment by AdrienPoupa** [comment]
Hi there,

As a rule of thumb, I start by checking if the application supports running in a subfolder. It is much easier when it does (Sonarr, Radarr), otherwise I need to tinker with Traefik config to make it work (qBittorrent) and it can get really ugly (Jellyseerr).

The benefit of using a reverse proxy such as Traefik is that you don't need to share ports to your host for new services, as only Traefik will need to connect to the services (User -> Traefik on ports 80/443 -> Pigallery).

Syncthing has this [documentation](https://docs.syncthing.net/users/reverseproxy.html) that could serve as a base to start the implementation:.

Based on [this](https://techoverflow.net/2023/10/27/syncthing-docker-compose-setup-using-traefik-as-reverse-proxy-with-http-basic-auth/), maybe this would work:

```yml
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - ./syncthing:/var/syncthing
    ports:
      - "22000:22000"
      - "21027:21027/udp"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.syncthing.rule=(Host(`${HOSTNAME}`) && PathPrefix(`/syncthing`))
      - traefik.http.routers.syncthing.tls=true
      - traefik.http.routers.syncthing.tls.certresolver=myresolver
      - traefik.http.services.syncthing.loadbalancer.server.port=8384
```
