### ISSUE TITLE
Jackett Support - Compose issue: blank page 

### ISSUE THREAD

**Issue by ogamingSCV** [AdrienPoupa/docker-compose-nas#84]
Fist of all I absolutely love the Projekt you are putting together here and the love you give it! 

Currently I am trying to implement Jackett my self, by referencing the other services as a start point, but I seam to be stuck at some traefik configs (I think). 
The container starts with no issue (all logs look fine), but I only get a blank page or the `Application error: a client-side exception has occurred (see the browser console for more information).` Error that I had with other services a few times as well. 

This is the added portion on my `docker-compose.yml`:
```yml
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - AUTO_UPDATE=true
    volumes:
      - ${CONFIG_ROOT:-.}/jackett:/config
      - ${DATA_ROOT}:/downloads
    #ports:
    #  - 9117:9117
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:9117/jackett/UI"]
      interval: 30s
      retries: 10
    labels:
      - traefik.enable=true
      - traefik.http.routers.jackett.rule=(Host(`${HOSTNAME}`) && PathPrefix(`/jackett`))
      - traefik.http.routers.jackett.tls=true
      - traefik.http.routers.jackett.tls.certresolver=myresolver
      - traefik.http.services.jackett.loadbalancer.server.port=9117

      #- "traefik.http.routers.transmission.service=transmission"
      #- "traefik.http.routers.jackett.service=jackett"

      #- "traefik.http.routers.jackett.entrypoints=https"
      #- "traefik.http.routers.jackett.middlewares=forward-auth"

      - homepage.group=Media
      - homepage.name=Jackett
      - homepage.icon=jackett.png
      - homepage.href=/jackett
      - homepage.description=Indexers management
      - homepage.weight=6
      - homepage.widget.type=jackett
      - homepage.widget.url=http://vpn:8989
      #- homepage.widget.key=${JACKETT_API_KEY}
      #- homepage.widget.password=
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy
```

Maybe someone can help me with this addition so it might also get integrated into the main Project. I have not seen any reference to Jackett yet. 

Cheers!
